name: CI CD Pipeline

on:
    push:
        branches:
            - main
              # - "**"

jobs:
    test:
        name: Run Tests Actions
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "22"

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install Dependencies
              run: pnpm install

            - name: Run Tests
              run: pnpm run ci:fix

            - name: Build Application
              run: pnpm run build
    # build:
    #     name: Build Application
    #     runs-on: ubuntu-latest

    # depoly:
    #     name: Deploy Application
    #     runs-on: ubuntu-latest
